import { useState } from "react";
import { FileText, Download, AlertCircle, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import { useApp } from "@/context/AppContext";
import { toast } from "sonner";
import jsPDF from "jspdf";

export const HealthReportGenerator = () => {
  const [generating, setGenerating] = useState(false);
  const { insights, userName, reportGenerated, setReportGenerated, addLog } = useApp();

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);
      setReportGenerated(true);
      addLog({ type: "report", actor: userName || "Patient", action: "Report generated", detail: "Health Insight Report created with compliance verification" });
      toast.success("Health Insight Report generated successfully");
    }, 2000);
  };

  const handleDownload = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 120, 100);
    doc.text("Living Health DNA", pageWidth / 2, 25, { align: "center" });
    doc.setFontSize(14);
    doc.setTextColor(60, 60, 60);
    doc.text("Health Insight Report", pageWidth / 2, 35, { align: "center" });

    // Patient info
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text(`Patient: ${userName || "Anonymous"}`, 20, 50);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 57);

    // Disclaimer
    doc.setFontSize(9);
    doc.setTextColor(180, 80, 60);
    doc.text("DISCLAIMER: This is NOT a medical diagnosis. All insights are pattern-based", 20, 70);
    doc.text("observations that should be reviewed by a qualified healthcare professional.", 20, 76);

    let y = 90;
    doc.setDrawColor(200, 200, 200);
    doc.line(20, y - 4, pageWidth - 20, y - 4);

    // Insights
    insights.forEach((insight) => {
      if (y > 250) {
        doc.addPage();
        y = 25;
      }
      doc.setFontSize(13);
      doc.setTextColor(40, 40, 40);
      doc.text(insight.title, 20, y);
      y += 7;

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Risk Level: ${insight.riskLevel}  |  Confidence: ${insight.confidence}%`, 20, y);
      y += 6;

      doc.setFontSize(9);
      const summaryLines = doc.splitTextToSize(insight.summary, pageWidth - 40);
      doc.text(summaryLines, 20, y);
      y += summaryLines.length * 5;

      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      doc.text(`Generated by: ${insight.agents.join(", ")}`, 20, y);
      y += 5;
      doc.text(`Data sources: ${insight.dataSources.join(", ")}`, 20, y);
      y += 10;

      doc.setDrawColor(220, 220, 220);
      doc.line(20, y - 4, pageWidth - 20, y - 4);
    });

    // Footer
    y += 5;
    if (y > 260) { doc.addPage(); y = 25; }
    doc.setFontSize(10);
    doc.setTextColor(40, 120, 100);
    doc.text("Recommended: Consult a specialist for medical validation.", 20, y);
    y += 7;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Compliance Agent verified — safe for sharing", 20, y);

    const fileName = `${(userName || "patient").replace(/\s+/g, "_")}_health_report.pdf`;
    doc.save(fileName);
    toast.success(`Downloaded ${fileName}`);
  };

  return (
    <div className="bg-card rounded-2xl border border-border shadow-card p-6">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-10 h-10 rounded-full bg-dna-warm/15 flex items-center justify-center">
          <FileText className="h-5 w-5 text-dna-warm" />
        </div>
        <div>
          <h3 className="font-display font-bold text-lg">Health Insight Report</h3>
          <p className="text-sm text-muted-foreground">Generate a compliance-safe report</p>
        </div>
      </div>

      <div className="p-4 rounded-xl bg-muted/50 border border-border mb-4 text-sm space-y-2">
        <p className="font-medium">Report will include:</p>
        <ul className="space-y-1 text-muted-foreground text-xs">
          <li>• Patient name and health timeline</li>
          <li>• Risk insights with confidence scores (NOT diagnoses)</li>
          <li>• Explainable AI reasoning per insight</li>
          <li>• Color-coded affected areas</li>
          <li>• Recommended specialist consultation</li>
        </ul>
      </div>

      <div className="flex items-start gap-2 p-3 rounded-xl bg-risk-moderate/8 border border-risk-moderate/15 mb-4">
        <AlertCircle className="h-4 w-4 text-risk-moderate mt-0.5 shrink-0" />
        <p className="text-xs text-muted-foreground">
          <strong className="text-foreground">Disclaimer:</strong> This is not a medical diagnosis. All insights are pattern-based observations that should be reviewed by a qualified healthcare professional.
        </p>
      </div>

      <div className="flex items-center gap-1.5 text-xs text-dna-teal mb-4">
        <ShieldCheck className="h-3.5 w-3.5" />
        <span>Compliance Agent verified — safe for sharing</span>
      </div>

      {!reportGenerated ? (
        <Button className="w-full" onClick={handleGenerate} disabled={generating || insights.length === 0}>
          {generating ? (
            <motion.span animate={{ opacity: [1, 0.5, 1] }} transition={{ repeat: Infinity, duration: 1 }}>
              Agents generating report...
            </motion.span>
          ) : insights.length === 0 ? (
            "Run analysis first to generate report"
          ) : (
            <>
              <FileText className="h-4 w-4 mr-2" />
              Generate Health Insight Report
            </>
          )}
        </Button>
      ) : (
        <Button variant="outline" className="w-full" onClick={handleDownload}>
          <Download className="h-4 w-4 mr-2" />
          Download Report (PDF)
        </Button>
      )}
    </div>
  );
};
