import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, AlertTriangle, ShieldCheck, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";

interface RiskInsight {
  id: string;
  title: string;
  riskLevel: "Low" | "Moderate" | "High";
  confidence: number;
  summary: string;
  explanation: string;
  dataSources: string[];
  agents: string[];
  requiresValidation?: boolean;
}

const riskColorMap = {
  Low: "bg-risk-low/15 text-risk-low border-risk-low/20",
  Moderate: "bg-risk-moderate/15 text-risk-moderate border-risk-moderate/20",
  High: "bg-risk-high/15 text-risk-high border-risk-high/20",
};

const riskBarMap = {
  Low: "bg-risk-low",
  Moderate: "bg-risk-moderate",
  High: "bg-risk-high",
};

export const RiskInsightCard = ({ insight }: { insight: RiskInsight }) => {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="bg-card rounded-2xl border border-border shadow-soft overflow-hidden">
      <div className="p-5">
        <div className="flex items-start justify-between gap-3 mb-3">
          <h4 className="font-display font-semibold">{insight.title}</h4>
          <span className={`px-2.5 py-0.5 rounded-full text-xs font-medium border ${riskColorMap[insight.riskLevel]}`}>
            {insight.riskLevel} Risk
          </span>
        </div>

        {/* Confidence bar */}
        <div className="mb-3">
          <div className="flex justify-between text-xs text-muted-foreground mb-1">
            <span>Confidence</span>
            <span>{insight.confidence}%</span>
          </div>
          <div className="h-2 bg-muted rounded-full overflow-hidden">
            <motion.div
              className={`h-full rounded-full ${riskBarMap[insight.riskLevel]}`}
              initial={{ width: 0 }}
              animate={{ width: `${insight.confidence}%` }}
              transition={{ duration: 1, ease: "easeOut" }}
            />
          </div>
        </div>

        <p className="text-sm text-muted-foreground mb-3">{insight.summary}</p>

        {/* Agents contributed */}
        <div className="flex items-center gap-1.5 flex-wrap mb-3">
          <span className="text-xs text-muted-foreground">Generated by:</span>
          {insight.agents.map((a) => (
            <span key={a} className="text-xs px-2 py-0.5 rounded-full bg-accent text-accent-foreground">{a}</span>
          ))}
        </div>

        {/* Compliance badge */}
        <div className="flex items-center gap-1.5 text-xs text-dna-teal">
          <ShieldCheck className="h-3.5 w-3.5" />
          <span>Verified by Compliance Agent</span>
        </div>

        {insight.requiresValidation && (
          <div className="mt-3 p-3 rounded-xl bg-risk-high/8 border border-risk-high/15">
            <div className="flex items-center gap-2 mb-2">
              <AlertTriangle className="h-4 w-4 text-risk-high" />
              <span className="text-sm font-medium text-risk-high">This insight requires medical validation</span>
            </div>
            <Button size="sm" variant="outline" className="text-xs">
              <Share2 className="h-3 w-3 mr-1.5" />
              Share with Specialist
            </Button>
          </div>
        )}
      </div>

      {/* Expandable explanation */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-center gap-1.5 py-3 border-t border-border text-xs text-muted-foreground hover:bg-muted/50 transition-colors"
      >
        <span>Why this insight was generated</span>
        <ChevronDown className={`h-3.5 w-3.5 transition-transform ${expanded ? 'rotate-180' : ''}`} />
      </button>
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0 }}
            animate={{ height: "auto" }}
            exit={{ height: 0 }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 pt-2 border-t border-border bg-muted/30">
              <p className="text-sm text-muted-foreground mb-3">{insight.explanation}</p>
              <div>
                <p className="text-xs font-medium mb-1.5">Data sources used:</p>
                <div className="flex flex-wrap gap-1.5">
                  {insight.dataSources.map((s) => (
                    <span key={s} className="text-xs px-2 py-0.5 rounded bg-secondary text-secondary-foreground">{s}</span>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
