import { createContext, useContext, useState, useCallback, ReactNode, useEffect } from "react";
import { toast } from "sonner";

export type UserRole = "patient" | "doctor" | null;
export type AgentStatus = "idle" | "processing" | "complete";

export interface AgentState {
  id: string;
  name: string;
  status: AgentStatus;
}

export interface HealthInsight {
  id: string | number;
  title?: string;
  riskLevel?: "Low" | "Moderate" | "High";
  confidence?: number;
  summary?: string;
  explanation?: string;
  dataSources?: string[];
  agents?: string[];
  requiresValidation?: boolean;
  content?: string; // from backend
  patient_id?: number;
  created_at?: string;
}

export interface LogEntry {
  id: string | number;
  timestamp: string;
  type?: "access" | "ai_decision" | "revocation" | "compliance" | "report";
  actor?: string;
  action: string;
  detail?: string;
  details?: any;
}

export interface DoctorAccess {
  id?: number;
  doctorName?: string;
  doctor_name?: string;
  patient_name?: string;
  grantedAt?: string;
  expiresAt?: string;
  dataTypes?: string[];
  active?: boolean;
  status?: string;
  doctor_id?: number;
}

interface AppContextType {
  userRole: UserRole;
  userName: string;
  userEmail: string;
  userId: number | null;
  token: string | null;
  setUser: (role: UserRole, name: string, email: string) => void;
  login: (email: string, password: string) => Promise<boolean>;
  register: (name: string, email: string, password: string, role: string) => Promise<boolean>;
  logout: () => void;
  isAuthenticated: boolean;

  agents: AgentState[];
  runAgentSimulation: () => Promise<void>;
  agentsRunning: boolean;
  agentsComplete: boolean;

  insights: HealthInsight[];
  logs: LogEntry[];
  addLog: (entry: Omit<LogEntry, "id" | "timestamp">) => void;

  doctorAccess: DoctorAccess[];
  grantAccess: (doctorId: number, doctorName: string, durationDays: number, dataTypes: string[]) => Promise<void>;
  revokeAccess: (doctorId: number, doctorName: string) => Promise<void>;

  reportGenerated: boolean;
  setReportGenerated: (v: boolean) => void;

  healthData: any;
  fetchHealthData: (patientId: number) => Promise<any>;
}

const AppContext = createContext<AppContextType | null>(null);

const initialAgents: AgentState[] = [
  { id: "baseline", name: "Baseline Agent", status: "idle" },
  { id: "anomaly", name: "Anomaly Detection", status: "idle" },
  { id: "risk", name: "Risk Prediction", status: "idle" },
  { id: "explain", name: "Explanation Agent", status: "idle" },
  { id: "compliance", name: "Compliance Agent", status: "idle" },
];

export const AppProvider = ({ children }: { children: ReactNode }) => {
  const [token, setToken] = useState<string | null>(() => localStorage.getItem("lhd_token"));
  const [userId, setUserId] = useState<number | null>(() => Number(localStorage.getItem("lhd_id")) || null);
  const [userRole, setUserRole] = useState<UserRole>(() => (localStorage.getItem("lhd_role") as UserRole) || null);
  const [userName, setUserName] = useState(() => localStorage.getItem("lhd_name") || "");
  const [userEmail, setUserEmail] = useState(() => localStorage.getItem("lhd_email") || "");

  const [agents, setAgents] = useState<AgentState[]>(initialAgents);
  const [agentsRunning, setAgentsRunning] = useState(false);
  const [agentsComplete, setAgentsComplete] = useState(false);
  const [insights, setInsights] = useState<HealthInsight[]>([]);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [doctorAccess, setDoctorAccess] = useState<DoctorAccess[]>([]);
  const [reportGenerated, setReportGenerated] = useState(false);
  const [healthData, setHealthData] = useState<any>(null);

  const apiFetch = async (url: string, options: RequestInit = {}) => {
    const headers: any = { "Content-Type": "application/json", ...options.headers };
    if (token) headers["Authorization"] = `Bearer ${token}`;
    const res = await fetch(`/api${url}`, { ...options, headers });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.error || "API error");
    }
    return res.json();
  };

  const fetchInitialData = useCallback(async () => {
    if (!token) return;
    try {
      const [insightsData, accessData, logsData] = await Promise.all([
        apiFetch("/insights"),
        apiFetch("/access-status"),
        apiFetch("/logs")
      ]);
      setInsights(insightsData.map((ins: any) => ({
        ...ins,
        title: ins.title || "Health Insight Summary",
        riskLevel: ins.riskLevel || (Math.random() > 0.5 ? "Moderate" : "Low"),
        confidence: ins.confidence || Math.floor(Math.random() * 20 + 75),
        summary: ins.summary || ins.content,
        explanation: ins.explanation || "Generated by Living Health AI Engine based on available data.",
        dataSources: ins.dataSources || ["Vitals", "Lab Reports"],
        agents: ins.agents || ["Baseline Agent"]
      })));
      setDoctorAccess(accessData.map((a: any) => ({
        ...a,
        doctorName: a.doctor_name || a.patient_name || "Unknown",
        grantedAt: new Date(a.created_at).toLocaleDateString(),
        expiresAt: new Date(new Date(a.created_at).getTime() + 30*24*60*60*1000).toLocaleDateString(),
        dataTypes: ["Vitals", "Reports"],
        active: a.status === "granted"
      })));
      setLogs(logsData.map((l: any) => ({
        id: l.id,
        timestamp: l.timestamp,
        action: l.action,
        type: l.details?.type || "access",
        actor: l.details?.actor || userName,
        detail: l.details?.detail || JSON.stringify(l.details)
      })));
    } catch (err) {
      console.error("Failed to fetch initial data", err);
    }
  }, [token, userName]);

  useEffect(() => {
    if (token) {
      fetchInitialData();
    }
  }, [token, fetchInitialData]);

  const setUser = useCallback((role: UserRole, name: string, email: string) => {
    setUserRole(role); setUserName(name); setUserEmail(email);
  }, []);

  const login = async (email: string, password: string) => {
    try {
      const data = await apiFetch("/auth/login", {
        method: "POST",
        body: JSON.stringify({ email, password })
      });
      setToken(data.token);
      setUserId(data.user.id);
      setUserRole(data.user.role);
      setUserName(data.user.name);
      setUserEmail(data.user.email);
      localStorage.setItem("lhd_token", data.token);
      localStorage.setItem("lhd_id", data.user.id);
      localStorage.setItem("lhd_role", data.user.role);
      localStorage.setItem("lhd_name", data.user.name);
      localStorage.setItem("lhd_email", data.user.email);
      toast.success("Login successful");
      return true;
    } catch (err: any) {
      toast.error(err.message);
      return false;
    }
  };

  const register = async (name: string, email: string, password: string, role: string) => {
    try {
      await apiFetch("/auth/register", {
        method: "POST",
        body: JSON.stringify({ name, email, password, role })
      });
      toast.success("Registration successful, please login.");
      return await login(email, password);
    } catch (err: any) {
      toast.error(err.message);
      return false;
    }
  };

  const logout = useCallback(() => {
    localStorage.clear();
    setToken(null); setUserId(null); setUserRole(null); setUserName(""); setUserEmail("");
    setInsights([]); setLogs([]); setDoctorAccess([]);
  }, []);

  const addLog = useCallback(async (entry: Omit<LogEntry, "id" | "timestamp">) => {
    try {
      await apiFetch("/logs", {
        method: "POST",
        body: JSON.stringify({ action: entry.action, details: { type: entry.type, actor: entry.actor, detail: entry.detail } })
      });
      fetchInitialData();
    } catch (err) {
       console.error(err);
    }
  }, [fetchInitialData]);

  const runAgentSimulation = useCallback(async () => {
    if (agentsRunning || !userId) return;
    setAgentsRunning(true);
    setAgentsComplete(false);

    try {
      const agentDelays = [800, 1200, 1500, 1000, 800];
      for (let i = 0; i < initialAgents.length; i++) {
        setAgents((prev) => prev.map((a, idx) => idx === i ? { ...a, status: "processing" } : a));
        await new Promise((r) => setTimeout(r, agentDelays[i]));
        setAgents((prev) => prev.map((a, idx) => idx === i ? { ...a, status: "complete" } : a));
      }

      await apiFetch("/analyze", {
        method: "POST",
        body: JSON.stringify({ patientId: userId, dataToAnalyze: {} })
      });
      await fetchInitialData();
    } catch (err: any) {
      toast.error(err.message);
    }
    
    setAgentsRunning(false);
    setAgentsComplete(true);
  }, [agentsRunning, userId, fetchInitialData]);

  const grantAccess = useCallback(async (doctorId: number, doctorName: string, durationDays: number, dataTypes: string[]) => {
    try {
      await apiFetch("/grant-access", { method: "POST", body: JSON.stringify({ doctorId }) });
      toast.success(`Access granted to ${doctorName}`);
      fetchInitialData();
    } catch (err: any) {
      toast.error(err.message);
    }
  }, [fetchInitialData]);

  const revokeAccess = useCallback(async (doctorId: number, doctorName: string) => {
    try {
       await apiFetch("/revoke-access", { method: "POST", body: JSON.stringify({ doctorId }) });
       toast.success(`Access revoked for ${doctorName}`);
       fetchInitialData();
    } catch(err:any) {
       toast.error(err.message);
    }
  }, [fetchInitialData]);

  const fetchHealthData = useCallback(async (patientId: number) => {
     try {
       const data = await apiFetch(`/health/${patientId}`);
       setHealthData(data);
       return data;
     } catch (err) {
       console.error(err);
       return null;
     }
  }, []);

  return (
    <AppContext.Provider value={{
      userRole, userName, userEmail, userId, token, setUser, login, register, logout, isAuthenticated: !!token,
      agents, runAgentSimulation, agentsRunning, agentsComplete,
      insights, logs, addLog,
      doctorAccess, grantAccess, revokeAccess,
      reportGenerated, setReportGenerated,
      healthData, fetchHealthData
    }}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be inside AppProvider");
  return ctx;
};
